<?php

/**
 * @file
 * Module file for Housing Schemes Services.
 * Contains the resource declarations for the service APIs
 * and other commons functions/hooks. if necessary
 */

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data.
 */
function file_scan_services_services_resources() {
  $resources = array();

//Include the necessary inc files.
  module_load_include('inc', 'file_scan_services', 'includes/file_scan.services');

//Service Apis for contents.
  $resources += file_scan_services_resource();

  return $resources;
}